### ISSUE TITLE
下载词库内不包含简码

### ISSUE THREAD

**Issue by qwertyyb** [yutent/wb-table#1]
下载词库内没有简码似乎不太符合预期

**Comment by yutent** [comment]
> 下载词库内没有简码似乎不太符合预期

什么样的简码?  我目前是按照`清歌输入法`的词库格式生成的, 而且我看了一下, 你那个输入法使用的格式跟`清歌`是一样的

**Comment by yutent** [comment]
![image](https://user-images.githubusercontent.com/11972650/159389138-ced8907a-ef96-4448-a888-fb1191377abd.png)
一级简码~四级简码, 都有的呀, 只是排序是按中文的来了, 不是按简码的来, 所以在最上面没看到而已

**Comment by qwertyyb** [comment]
哎，我这里下载的，没有包含这个简码

**Comment by yutent** [comment]
> 哎，我这里下载的，没有包含这个简码

下载有2个文件,  可能有一个被浏览器拦截了, 应该有个提示 "允许多文件下载" 的
